apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service
  namespace: fitforge-prod
  labels:
    app: ai-agent-service
    app.kubernetes.io/name: ai-agent-service
    app.kubernetes.io/part-of: fitforge
spec:
  type: {{ (index .Values.services .Chart.Name).service.type }}
  selector:
    app: ai-agent-service
  ports:
    - name: http
      port: {{ (index .Values.services .Chart.Name).service.port }}
      targetPort: {{ (index .Values.services .Chart.Name).service.targetPort }}
      protocol: TCP
