apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: fitforge-gateway
      namespace: fitforge-dev
  rules:
  - matches:
      - path:
          type: Exact
          value: /argo
      - path:
          type: PathPrefix
          value: /argo/
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
    backendRefs:
      - name: argocd-server
        port: 80