apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: fit-forge
  labels:
    app: auth-service
type: Opaque
stringData:
  MONGO_URI: "mongodb://auth_user:password%2FccwLL@mongodb-0.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-1.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-2.mongodb-headless.fit-forge.svc.cluster.local:27017/auth_db?replicaSet=rs0"
  JWT_SECRET: "alongtext"
