# ai-agent-service values
replicaCount: 1

image:
  repository: aswin018/k8s_mern_app_ai-agent-service
  pullPolicy: Always
  # ── Update this tag in CI after a successful build & push ─────────────────
  tag: "v5"

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

service:
  type: ClusterIP
  port: 5006
  targetPort: 5006

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

networkPolicy:
  enabled: true
