---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: progress-service-secret
  namespace: fitforge-dev
spec:
  encryptedData:
    JWT_SECRET: AgCBB0PrfuWiu9uDEsPSfj6ykuJZc0pBvpFHRzIESvgFtkwAYrKEc6dDNNFHKeLG7zDX+8PTJGQsFBbBatfvaCJvX/G4PppdT4TptgFspwEj2xksJN19rF1/xPs18zxHEP7ZPx60xG4YOm5uOm1Ij1XwMCoJxji+6Ha9PSrFEVfshC48M7IETk6t6HYuCPqdJ0LyMCHq7bM+DDVtWbDJi+h+L4pjFYWn0w8tI77zdDhUR3FDRo/zHMmKc3Gj3cynGvh/kbgrzFFZjwito06Y2knoCRHggEzyuNeBHTX9iHiykFkM0mVCstxn+qVv54ShdCAaYG8GVYVH1HDVGVlj4tkzFB1QR1qyAbJ5k0XByNXUeVFY7C8sn+ZOSo59eNQdspCQ6FljCSgep+NAKMYN1IgshMQq8pr29AkFyeX+emWQdc7OaqtKRHce5CrB+nrADtYXmWvGWGvOmtc0PaPVOYHvI04RocH7PdfNcnFONBKxPid63CWYY6tvORi2cmmO16Xf0SXMV/AXdENBZybdY2AgURuZ0rRlTJE4nsEvdsetlrHK3f8jQQA7K2f5EutWktqyYpW++2wDU7jtsJLnlKU8PEctlR+qyliNMxK5FB42X1vY5Vz4lKwOhBuhpeqkDmq8/txcL/joJ6DlHNbiX5rxkkiZwqunzNs/DmJXtmFVBeMqOmtSfktreFj6dre4h59myGaeayXIqiSH8/C7KWkSq9XLbzZ4pIN2sAEWuCGjTj1a
    MONGO_URI: AgDFv7tHIpVuZlP3ykJB0+WrxlWvxN942X3mjc6qVtxAQsB+9hpt8vH+nI1FAih3uNE6sqGh0wlvcCxORQD4rjTXKbzEtNWWIInHiOVXZDlf3r/VVXMYxnN1m5iK+x2uIxnMyfltmiTILCI8x4Zd22ZQSJNAU64zMGv1ZjuhxQI6vCvYJYrHTRz5gWsnQeZsIBBIV/2pEeKNxK/mh+YEix3HfGsKv0U7O3M8dB6CqVrx7BZ9lZahw340x13d6Z0NNtBcYrCOt7pBrHY5nMB4zFZu93k13wjwYZFppbh8xSY99e4ZrisH1RRvJuls2cV53wysDvnpQ6KSiFI3Q3QxNDozPRFvv8ijvFmTeYv7B/IaxJtL3od+UUcFfppvA5j4J+CZHUZ7aK2gCgyI+X8V9rRq7jbUdY5ONdVDPefvLYAjFQpxIzeqWaaLZE7x5zmfRY3nlc62iiQC5e7x+lrf53dMPiMYiVDyL1c5lplFoBnH2FlHZuB78X2VOZH6WVVbCTUMtTT5t/5xSNn/WvWKIDyIFSjGBubUijhecdNta51AizORPgz/fZj0GroD8x00pIHmbxfTMg6t+9qdBxFQ+vrpNIr6c/jzABw9XECAch6N273/yPwxAuwi9xMc+3mP0FVK8/EAiwaQuKShmoo6rWyMaPIinxdR+fNTHtr9OrfjDosMZpH1OTeNiigwpYVNXslgLw3FpDZ7fehFiG5RwK13ETizxWJApxDCpiRmLJ7TDG7mmO1jjrM+Jylr9hZVzMNCSl/MbpCpSzOfExM0wjhuLADXN543L61ZJxfOlijC127hp1qBRbDnzym09TrZcVfp+Gu2xw2c7l8Egrl/P4bwhJparUmDAv8AvKtbDBuZv/3+
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: progress-service
      name: progress-service-secret
      namespace: fitforge-dev
    type: Opaque
