---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: progress-service-secret
  namespace: fitforge-prod
spec:
  encryptedData:
    JWT_SECRET: AgDSUV9izQPu7s7A0efr2qfdkTP7RxoN1TBmt4YYFBiXNmTgTMH52NmZSqmAIopU9AMQaG7cW/K3pjk7qJce6z2usigwYJB5PE1GFXLIXdv0E/jRVB3xYibb2jJ3bEuwTpcNo8foWr0f1PU732BmE8R1kB00h35YroseInDBa/5zN+kNy9GrSY+bjgXOaFiVXvQprM0UEiT4CSo+klMqJ1F2qrYZ9gIChqI4IOSkIuNjMQnngWayOC3bwwTu0mnFq/USPXa8bHqqWmoWnySrdm9UGAKYIvlR1WQTIUNBCdcDh3ieRwIWBVtjXrphT1M+N9AcNICqpSSCmhyPchACHGXx3uuDbK2o+GQSXie4zxppyq9L0PhwQ9TeR/EARt4F7vqADbkzoa4G8nktLRC/KxGKGRlXBDzjVV3xYhaVen1oe0L1KV3r+Ou69VLXJDGNO4cuG+bsyxGAPADOV+5bxgcb8MzJrdiFklgm8Jp3NHW+s+4DFP8TCCpXFmhnCwvQM7VDhZE2XeewRYHAWzwTHBLdhH8B+yftCouy5Dlv9xaIK0+84b2SlABxqcM5OQECAa/kZEx2bMEbwHBJ5pp5DVPhaNZthophOxqzSppu4BXwaQQp/4dK/OFGxF5jg/kMtwTvpDCAINMVYxqkyCx+RxhTXjk/aWqhRwkd9hqR+DdeMx5/T0qyMwDJ/lC8LggKZj5qqccnqnRtPLiKH+IIA5hjDj/euT6HzXXrS0jwgmoqBWeE
    MONGO_URI: AgA49SJytlxvTkN1sZZWfV9n9jzLCOAbYd3TkuoJQF/FDNzohyxv8mmBqOYf1aSK169hpxE4bn2ldztWJbUfixm5UlCBAsTYYvKSGzMsPLL+zE5aFGsdCcMnUeguaCtL7iNNz/Ice7X8bfRcIkXbV2SXwTAl8ECo9nRnx6T6KKk4yrYNiaS4VZo7DLFbRG/X5twYsrvBiRxRhvnfTPMPZ/Zt0hxd037kr+wDJk0SHzmb9HFJC3Su/XvEQk+U5aF+NU7EDskaaPPZiIdgWVlsDwjhE+N5U3ET7AIfkYvzADh5xciG9+gT1qBzGOseo9ir1AW3JUpQmGQuNq/CIGWRtX8pXQrluz9IYeN3UHQPH976pwQNIuA5ETYOOBGl1AeblbmhnNCXA2H7NwVRkexWncYgnMdnJl9lyOI5IoFbZDmY/qEuJFMDbzVCChiIopCnUenzkrSVnmMoWbR6v3l3oVa318wJOpZoCWp8wjtwlRgVzZ/ifZfWVtdQn6FqtO9j30wJM/6Uc2omuG1RhY3W5cNgGhYwl+S+KL7xfqmly7qZ+JHZLttWqvzwmdhO7uG5xwPEqhhaPZ+KpgeGqEtTjOduB1Y/uN2zfgkvtgXv08fobdl28oFj/O0J7JVzcboT82o27N/6yctZ7b0Qkouvvfy6n3dvLV8qIjaBTPLu2hjHNKXb6nDZEH8i/cgFEQwf5MtZlcHHtQYMQr9qbPwE/FIAfLYxV41XkavaQ6ASB4o1f9c38ceZu2wzMw0hvDoOhtbCk6eMGbInqGWVd7pGkqNp9YGkHho+K86mTFt5GjHvm3mU3xzGpSjtMF8RhLvTM8wQ/IwsMi+L/dY7c2+XDcihc/Z+bqeylVme4C1D1FC1zmZWmGQ=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: progress-service
      name: progress-service-secret
      namespace: fitforge-prod
    type: Opaque
