apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-service
  namespace: fitforge-prod
  labels:
    app: nutrition-service
    app.kubernetes.io/name: nutrition-service
    app.kubernetes.io/part-of: fitforge
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: nutrition-service
  template:
    metadata:
      labels:
        app: nutrition-service
        app.kubernetes.io/name: nutrition-service
        app.kubernetes.io/part-of: fitforge
    spec:
      containers:
        - name: nutrition-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
          envFrom:
            - secretRef:
                name: nutrition-service-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
