apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-service
  namespace: fitforge-prod
  labels:
    app: nutrition-service
    app.kubernetes.io/name: nutrition-service
    app.kubernetes.io/part-of: fitforge
    app.kubernetes.io/component: backend
spec:
  {{- if not (index .Values.services .Chart.Name).autoscaling.enabled }}
  replicas: {{ (index .Values.services .Chart.Name).replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: nutrition-service
  template:
    metadata:
      labels:
        app: nutrition-service
        app.kubernetes.io/name: nutrition-service
        app.kubernetes.io/part-of: fitforge
    spec:
      containers:
        - name: nutrition-service
          image: "{{ (index .Values.services .Chart.Name).image.repository }}:{{ (index .Values.services .Chart.Name).image.tag }}"
          imagePullPolicy: {{ (index .Values.services .Chart.Name).image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ (index .Values.services .Chart.Name).service.targetPort }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ (index .Values.services .Chart.Name).service.port }}"
          envFrom:
            - secretRef:
                name: nutrition-service-secret
          resources:
            {{- toYaml (index .Values.services .Chart.Name).resources | nindent 12 }}
