---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nutrition-service-secret
  namespace: fitforge-dev
spec:
  encryptedData:
    JWT_SECRET: AgB5AsvALsbY60RSoMiaill21Ovkj0/C/9CSh/19WEMcZRWC56AJ4Hz21PjFcIz2Z3IWnZwTIskpf5dgTv7wKlAS6+TqlWVXZugEtS+ygAFcMyZdVFOS484UIJH/Yu1aeIm0JkOoiPjkC7Wj9J24nojjY21jm8rTwfCZn5G+1ncPNMw3puQJ70z5l+RHhNkABeCafVq9RoNFfoVaE0NQTs/OFxLXvPrsqaqavprYPjQKI5qFc2BqV12bhcPe/2S9oK2zRWPPvN41J8g3MUdTZQRB7u3i8oPRXjgmR1CxsXX1MlrtizyJDTx4VVkKr6bLADcO34oPg8uDMxz6IGAnSnvvQtnAlnjXvNwR2ehMxriKL7KEIc5Xn6qH23Pd7BQml4+ncfdoYpg4eC6emJzT2yLI0HcWdlmu/ka6/CtPk5jKYbw4oxCReBFkv1e+dQeBj/d7vlZiqlcnI7OtVl1q61/1qk3poodA4JMceIBaxDrzAozNGUutUNY8t+iUUJJD4M01e15FrM4WQ5Jvkjz7oVIYhmBZbdSyugE9vgXASfiD2RoNS9NHwyKaIH0o2vaamfhq+RFAMFzy3yjw7PLWJiGkPbyq7UYFozBiLPtQ0x/+0pb29Wndl+UGrj+4WTGaBX8wohUKsrDyi+xDJBRaC2day/kpecw05zM2wnw6HOzIZtvGnVMMsXem7PZlFHiSZHdiv/xAR2sjmavv8sOXpo45nDdJZmLbdNdlOCEctRYe3xdE
    MONGO_URI: AgB6apnMvEaiP3Vu48WlOSr9wg0i6qEPYori6RTTYIX+HbG+o8VA70nw8rcCcipEOwRDO9bxqSg8hsgpVvwbdm0eS4xqvj7lAiaP3N75u4ExBLHyBYJrbupGw6B7o2sDNKazOW2zP+nHlqqtL7E4hlrq4q9LFAYQo5SFGm2C3G2VkC1XlVKQvayNGwvSinOP1f3A5tSXBCU6UBTQEhuCowCxLVbQU9SqVhIrBPepIefZQwb1yJpTL3IXnO/q9fRAfLh3PFtWGXlcINX7UOoXb9oLnm78z649eIzMHHdoDiox8/4aX3qXODBRilsxiNMxFHx4ny9kbFt+osiGeKT3YSze/oCOG1MIN0Keo/fHw0XMHFj1tDZTgcQGhNGSe1cLbd2zaCYWYUzVUW3FjlFSFIZ3ce1dbO5DotB2oxcnGidnHluB+mOp00S7z8xa6XWE5ZVCYjl6ub7xYXMZhTMcsjUBGVL3lk6enTcZv2hJOIj14mOdeDcyHofqeUEst4gbHG/UI46Ru3aD/V3SuDxltajxCLkmej7ktag56h7qd0TTRMkdKCkpXZ9eZhfPTlZElPDDIDnFB9HmgJX/HNlVpRHdJm25aqMhOAOff8uDMUMkh8SQVjNo5IMGU94cU+kHeVO58wpLBvuX0koc7F4mNnxsy5DtTtgtex2uGoKgXQmRc47+Q4fgZwDS6GUAg0681E4nKxhccLTNsc/vTNlVu1GHWOxtWPh4rSjXgRnZun0+i83Lx34oks7+/8zMsT0j/ZQsyviCIev7wiCUtNHv3dzO/5UZYcZ9p/8S5wjx3rnrcbz9XkSuglGVUld7aTwheTZ3dJAH6YokxzdJFjCCMBkay9YPDXQ+QWtTnyqhlFBB0v8vrgStx4Q=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nutrition-service
      name: nutrition-service-secret
      namespace: fitforge-dev
    type: Opaque
