apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: workout-service
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    app: workout-service
    app.kubernetes.io/name: workout-service
    app.kubernetes.io/part-of: fitforge
    app.kubernetes.io/component: backend
 
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.global.replicas.workoutService }}
  {{- end }}
 
  selector:
    matchLabels:
      app: workout-service
 
  template:
    metadata:
      labels:
        app: workout-service
        app.kubernetes.io/name: workout-service
        app.kubernetes.io/part-of: fitforge
 
    spec:
      containers:
        - name: workout-service
          image: {{ .Values.global.images.workoutService }}
 
          ports:
            - name: http
              containerPort: {{ .Values.global.ports.workoutService }}
 
          env:
            - name: PORT
              value: "{{ .Values.global.ports.workoutService }}"
 
          envFrom:
            - secretRef:
                name: workout-service-secret
 
          resources:
            requests:
              cpu: {{ .Values.global.resources.standard.requests.cpu }}
              memory: {{ .Values.global.resources.standard.requests.memory }}
            limits:
              cpu: {{ .Values.global.resources.standard.limits.cpu }}
              memory: {{ .Values.global.resources.standard.limits.memory }}
 
  strategy:
    blueGreen:
      activeService: workout-service-active
      previewService: workout-service-preview
 
      autoPromotionEnabled: {{ .Values.global.blueGreen.autoPromotionEnabled }}
      scaleDownDelaySeconds: {{ .Values.global.blueGreen.scaleDownDelaySeconds }}