# =============================================================================
# SealedSecret: workout-service-secret   (SAFE TO COMMIT TO GIT)
# =============================================================================
# Secrets needed: MONGO_URI, JWT_SECRET
#
# HOW TO GENERATE:
#   1. kubectl create secret generic workout-service-secret \
#        --namespace fit-forge \
#        --from-literal=MONGO_URI="mongodb://workout_user:<PASSWORD>@mongodb-0.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-1.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-2.mongodb-headless.fit-forge.svc.cluster.local:27017/workout_db?replicaSet=rs0" \
#        --from-literal=JWT_SECRET="<YOUR_STRONG_JWT_SECRET>" \
#        --dry-run=client -o yaml > /tmp/workout-service-secret.yaml
#   2. kubeseal --format yaml --controller-name sealed-secrets-controller \
#        --controller-namespace kube-system \
#        < /tmp/workout-service-secret.yaml \
#        > microservices/workout-service/templates/sealed-secret.yaml
#   3. rm /tmp/workout-service-secret.yaml
# =============================================================================

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workout-service-secret
  namespace: fitforge-dev
spec:
  encryptedData:
    JWT_SECRET: AgCk/y+zQeRRFBwx9p8dULcPT4nRUG91VcXeU9lKdqJ5Mxt1DVkyfuw3/uRD0/rn245XLvidmmtbwE3FEwLRWrrh0sy+zRjAnMuWD6BN80K816vZoGCC1mt9I3VRsbuF77bmAdb1NoNuGuJwmitaD9pe9xbgYyeHA2C1IhcTwMtgp0lLn5IKQloIv7xCWlEmeD22Jmr4nY92nSkDZS2OgyjhW9otFCNZVgSIn7wj/G4Euwn971hsTttYylt2jbRr/zr4SXfJQqnko3wTeW9jrp8AhAgDKuCI2I1viNCxx7mFTi2kzsn+QwW9wY/HphXNBhtidAs/0yYDZtw8wPzm7A1T55VZWz2u/jZhFQjDQyGSO4DLyF1Ln241/OKJtpq3Nnk3gPSRPNAYeMscacqgPAsgtIxiQe1sUOn/sPAuWov2yJ2KT6D1Qk2/OoaCuGBcAneoFJiAZnoHRLWfrxSKiitrLwYOqVE+t45NuGvKz+ULFA1oiE0g5V1KZRJqZ59L75XwlgNGeL1njeWRID+LoiBhGhDdzlKQJFYH0i36rJdgYcLDa6KQwAl8GBEZpWdDihPeOWw5WXZdks6UaeAAwYk/zrwsJStiyBJdrfHc7iMN4vYjaET/gFHZ2fZeq9V6+sHal95sv9I8Hiht0U2N/kS5DeFNzfNxDuRfQVDpkwfqjVMbeHYxG5nHQqnLTKkH+k3sxiUb7uzsUgh/+YhIHaniP16cZi3jXtiuQXUP5DuxWEJ6
    MONGO_URI: AgB0o+XPZaeDG2V8w6GOVW6SDWp0ptnnAL9Y8d7C/DpsUK8fvBxLlCvbfhB5PFVm8QWAdFG+rpYNRfe8kYSIOCBNPI/ElyGZWk8600BcDBY6iP+Dv/kvo38vC0Up3u3r1h0TX8Ua1fam5JRAHXDnh1/mA54fnKohtwGLn/L6Dbb2wjWnznWMA2AH1x7Oz4JcK8c+0l0VrtuU0lekS31KjRfrn1Yt/rz3W6H1iLJk86d48C0ALomb8gnxzZnHVbJL5m2KXPOuMC4+ZSnCfHdOV3e0chl7u4q5guFKjdIF9oVwyy7eUqe2A4ksNVN89xNk6cd+o7Dz4pQUrBUtMM26IN81LK4craJqWq7WYSsxipYZKp/Ua7DiS0nH++awYd7BF2PasUU98gOmsQxyfaHIHTdpRao1Bxg52OkvyurGtNQG8wq/fXtW9j7O/OycjsgF4XFpIQ48XDymVrfB6s9G5uHyP4D6agGfQRyz4QbV48h89sI+WaxCMaB54rSJrEDP8qQreM5oyh/qmCKUpSKPfDc+byMWrjN4QMlaA91iQEfCY1Ixl6GtaGP7lhFtTr1AJPSO9FY1ySLXCxaK1UHo1tImtOpOAswKk/JEr8Bkso2UDOdqLZhgNKjPBkGrRNXW0Kg/zqEqgfH4AFMdQNXMc+c38XH24wd7vG0JpzPkVpEk/BS3977hAxuAq/Ff/8JHOEBb2eQWFIuF383ehHvNldNNW03fTrngx7vNg9y12bjYohT5X2DuwRKMoemejG2+STTxoMJaaid3v6gIZ0xq3XDaG1PBDM0xFC6piVY4Sty34HEQPe8CzYVpzMZjHpkx5A59JOtLO0GuY1powZ+BSE4mP7k+0FJkz6yRdsiqMJ9gd+whfKHfbzLMcUNJO34u5qVSehw2KD/USVQVqdspNxJrloCc2kYyTkoFuvgajFTRuHOSiGDX4BcHx/QmFgyWQRPFoYjnlWomnonmSg2E/Xn0joJBuUKxTfJ0giQIAQB8jB+0EnON2i+dg5r0Qj0xmwXCgURVZEBHFj5y6gpDezpfz7ny3vgrJg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workout-service
      name: workout-service-secret
      namespace: fitforge-dev
    type: Opaque