---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workout-service-secret
  namespace: fitforge-dev
spec:
  encryptedData:
    JWT_SECRET: AgDbOtgqpy52vDhnp2eeVp/v+X78rtrnh0mhOZT1qe3LmvWOxrC9YGye5YYW8SN97fIwnwaKVqSKUfgOY9an4DDMHmT5H3RXZHNx+DzIbteX88Bwn2Fv5hpLr6q9wItrV1XXpcrk6ROhGfFnQHZifSMSVUFDassyDgLia2hxBiWqK4T5w3l4cY4UWDDFFM6Nbl5WcWVADwGIUCWD0sAwipUPZUC1tdSjSsaawTFHOvulytEMQjDf9Hm+HIC2km0mKKGQ65QczUgrdu3TIQ22r+rVJ7lfbKREWQJ5K3yigsAjXWc6ilcwwcLTZqvJMGNOH9oE6WQ/X/oySvAGdfW1i73z/YPH15DkHBSIyRLSZthfZvAUJDGNs1mYh9uJXzWez8YuxB6iG/UXIQl5IScpTbZSKajmyMR3pRR6hXm1xXgc0fIh6oAWmhu9WzxdsHjVDuVwEtHEABkDEai8fS29KCPzqxOvv5+9d7lSYTuLj9kcxiQLqbFnWegtGY6P9f23S1rgK66H1xRVb/zy+SfLToeWNoqbPaVvmUO1yeoxltYG04wCclK/K4sD6iJeqzpd/O1sTz63gKxoB/WxPGqNhVE+dGaGTwTz2PJbCis7VICvHCyjHSV0vxK69jMyHunYso8QCqCsB7V6TpFJgP/XeuQJMzAFkyNH8boYyVLhEVXg8WakLX/gjFGGjMtxD6kTk1nOalF4CHUhtnX4hSRDE0UAW0ch/wMwnnsBFgzLBYxTlgV7
    MONGO_URI: AgBiDD9mWaaHsYJwfi+Z8eziJSUfVRB33ieq4CYMsmtOhuARO0dbWt2JshtRYvzpKBache3flnZrZ/jBZKJ32+qQEJ47FQvuTsbT92XQyHxUo7x0QtlszWwykFgQlQfxPsZUUeWCgcSXwzaCj4CQBrFGUC0vcpExJMzxmSrWj+75hgvy0kqQRy/+22dW9/J/SzTrGbMZnVjGc+a7czVlJyTOhe4MTaAklVHDJQpRiPlCnUv4FdnbOslnYCxVjiEEZcnuvWSPv8P326CA0NVeYdjPSz6iyRt8S7HPfqXpsJHMVqq0HkGetTat86QOoX24OUswN/QlmlsDo+p5jQPYDj0d6cGHzMJlAEGlxjMcxv3d0YT6boxSrSN3/m+qh/GuQWOqRYiXJrEimyBy1E0VluJMRvoQfidexfMTeZNoLMTLNMnX0tot/IPeiJwss+X2AJrRtM6UtFHUcQMpdPA8r5YhRA8y6kmRhily1qw2hyANyTdDaL29cEWOQKaUD3QBTfakN76IEOFl2F0Y2nMXZOAVBiw8TGad3J3SffuQCYVHLNng6VbN/WQ9ituB5vGUR1J9YUGqRimWjrRYEHGtcotiQra57VhG5eDaSDmzn14FX/N3YZXcMew3jQn4b7JVI8SAqb5ELLuM6MXyZIvyR6RLlLEokYtHHgp3XxXeDU/DgZXkXUo1tPFJIaYAOxufUAWwChdUyDENx/gAXp0hVKP4sEHCohBrEzGISd2Pa5H9pQ61IdmZh0BT/AfT6DQmy5B0/cFIcPebhSLVyEgcJguLg4EeaYcXV28Xqoe1sB2r341cx5LEjN4yjCpQOlryz3D6w6Bmg5PNfh6TyimBG0TCPSEZeZC8pulZzyH5STom3EE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workout-service
      name: workout-service-secret
      namespace: fitforge-dev
    type: Opaque
