# ---
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   creationTimestamp: null
#   name: workout-service-secret
#   namespace: fitforge-prod
# spec:
#   encryptedData:
#     JWT_SECRET: AgDbOtgqpy52vDhnp2eeVp/v+X78rtrnh0mhOZT1qe3LmvWOxrC9YGye5YYW8SN97fIwnwaKVqSKUfgOY9an4DDMHmT5H3RXZHNx+DzIbteX88Bwn2Fv5hpLr6q9wItrV1XXpcrk6ROhGfFnQHZifSMSVUFDassyDgLia2hxBiWqK4T5w3l4cY4UWDDFFM6Nbl5WcWVADwGIUCWD0sAwipUPZUC1tdSjSsaawTFHOvulytEMQjDf9Hm+HIC2km0mKKGQ65QczUgrdu3TIQ22r+rVJ7lfbKREWQJ5K3yigsAjXWc6ilcwwcLTZqvJMGNOH9oE6WQ/X/oySvAGdfW1i73z/YPH15DkHBSIyRLSZthfZvAUJDGNs1mYh9uJXzWez8YuxB6iG/UXIQl5IScpTbZSKajmyMR3pRR6hXm1xXgc0fIh6oAWmhu9WzxdsHjVDuVwEtHEABkDEai8fS29KCPzqxOvv5+9d7lSYTuLj9kcxiQLqbFnWegtGY6P9f23S1rgK66H1xRVb/zy+SfLToeWNoqbPaVvmUO1yeoxltYG04wCclK/K4sD6iJeqzpd/O1sTz63gKxoB/WxPGqNhVE+dGaGTwTz2PJbCis7VICvHCyjHSV0vxK69jMyHunYso8QCqCsB7V6TpFJgP/XeuQJMzAFkyNH8boYyVLhEVXg8WakLX/gjFGGjMtxD6kTk1nOalF4CHUhtnX4hSRDE0UAW0ch/wMwnnsBFgzLBYxTlgV7
#     MONGO_URI: AgBiDD9mWaaHsYJwfi+Z8eziJSUfVRB33ieq4CYMsmtOhuARO0dbWt2JshtRYvzpKBache3flnZrZ/jBZKJ32+qQEJ47FQvuTsbT92XQyHxUo7x0QtlszWwykFgQlQfxPsZUUeWCgcSXwzaCj4CQBrFGUC0vcpExJMzxmSrWj+75hgvy0kqQRy/+22dW9/J/SzTrGbMZnVjGc+a7czVlJyTOhe4MTaAklVHDJQpRiPlCnUv4FdnbOslnYCxVjiEEZcnuvWSPv8P326CA0NVeYdjPSz6iyRt8S7HPfqXpsJHMVqq0HkGetTat86QOoX24OUswN/QlmlsDo+p5jQPYDj0d6cGHzMJlAEGlxjMcxv3d0YT6boxSrSN3/m+qh/GuQWOqRYiXJrEimyBy1E0VluJMRvoQfidexfMTeZNoLMTLNMnX0tot/IPeiJwss+X2AJrRtM6UtFHUcQMpdPA8r5YhRA8y6kmRhily1qw2hyANyTdDaL29cEWOQKaUD3QBTfakN76IEOFl2F0Y2nMXZOAVBiw8TGad3J3SffuQCYVHLNng6VbN/WQ9ituB5vGUR1J9YUGqRimWjrRYEHGtcotiQra57VhG5eDaSDmzn14FX/N3YZXcMew3jQn4b7JVI8SAqb5ELLuM6MXyZIvyR6RLlLEokYtHHgp3XxXeDU/DgZXkXUo1tPFJIaYAOxufUAWwChdUyDENx/gAXp0hVKP4sEHCohBrEzGISd2Pa5H9pQ61IdmZh0BT/AfT6DQmy5B0/cFIcPebhSLVyEgcJguLg4EeaYcXV28Xqoe1sB2r341cx5LEjN4yjCpQOlryz3D6w6Bmg5PNfh6TyimBG0TCPSEZeZC8pulZzyH5STom3EE=
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: workout-service
#       name: workout-service-secret
#       namespace: fitforge-prod
#     type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workout-service-secret
  namespace: fitforge-prod
spec:
  encryptedData:
    JWT_SECRET: AgCDrwGtN8Z4OqTkMcOER+6qobeHoKWAmddExIPoDJpcxdIJ3PKzpGk5h5oAezxFQN2cKnMTHrz8zxBKUGbC8AFSQ00c50hfK3UGdbUmkAbbU91n6QC7z7tHsi7II9DDS0e7vMT1EM+IzZD4+zE59mps2QnbzTlP22KMTgS1oawe9yHq0mWw5Bn36wIYHHxDU9QpBl3TV4lHk0J3lBA/TDXTLDnsSqWkz4H+tCMdMUoRpZfdSu0wMtI4JxBCwUIfnN4V1t445T+48lf5HiOdo+S88rdr1iLZAm3kgR4mbhbJnHzG04E+7CajD4BdjyXOwI0iEj7V9l02eCeqe88IDgae1pBQvhYwL49gugn3OYny7bZE8lrpzVfVf8Jl5frkUJuXnFDZi+z69uSIYv0U5KcstfhJIDMxU9mwd9JDTuY2LkKCj4cevX59t8x2kpyCQ77ZiCpg1CSt+TIewUbZgRC16rNZv5sZlVnZ3xBYOuURsvXJYnKRGIyuZKXosd+i9zGi3pl+oH27RGplepBSFEkjWsIHes9VXPADZExAjdAdF2AiS66lgduYFOQ8novLZUXXsgw4FjKxsvpYZ6BLmLGrgrzHeQMQxSGS9iEXoMFoRwBkQ09t6JXhvnU7BHC2/aThCZTiTnQwy4yRTKLiMUjZQN25vB7tPXz4sLvxATFWrBqhprQV4g9lcSNRQeX+m00zkH2xWneOqGh5QK8hRa7eUuHfELtyK4VqAF2daqJzSQyw
    MONGO_URI: AgDM+X2HoA3Q4QNePlisqE07RteOAKQi4frni95tcek5xKE/f4GqETetA+IfbMXkoOmeA5AUbHef8zZu2YFEWjkGnreAmBzyObZWTVqBWk5AI5rrQgXZuGhOJTgK8wRyNgZOqhbTdGmurTwubDKS6vWm3pjaO4M8EUsFcOparkA4cu+YLj4MxttG7IGxXJvRCX9wLG9txtEAOVjHl2iqYB0K9J6cve5ywKNd2lrrWQlg+HYVH+3TuwCPY7bdFOR0GXb/5te66uDHz533hekogPxc45ktEg+1UvzAVQCdk+C+Z2uHDa6CZrdF9MBZmiLtZf6+kkn5F3aIW/WBttlvcBK11QB/Sgy/bRj9AhjefFnnmQm6opBcf8Txdnp3YENnO0w9zfdOQWllxFnbTdJUYnxVHtzK4EGUW1aLCDsRn9zT28uDD5XN+XbJ65NGWwuDFev5zpTFvqKpnMzyqNTvKyIKcuT8l6mGLumS4RODsfoVToTtu9FonbYgOXdVZdx0f3pmWERRTmETYTQD0m7TopOfKquJipUA8jfnLhdcIERb0IjAuDR9QCzJRJ+eLpsQ0sSKd2OOiqRBt4i6FPrSzHxxu/zLzG2M+CPq42Vefh+3eOSGzc5RtlKA6Jp6v8SYIBPbTBu7bTMTTLUmXNQRrFtn41wZCy+DAKlBndRFKkUxNjDBxgUBaGxJQ+9XGfKbfypbslABnNW/42NR2bg3CQAeqbSzJE/3HNs8gRvV2FjAP0tnbxROUPvzXD0VJToKMnUZ+44lNOjKbJdQGftzryKsVDeR7vYFSk7AsvXGrKfoerKSIZMpFIShlp5KGFDZaT2I47em0jUBFP8G91cbNx8w/W8OEyhBIyKZ+86HoY3yXD8W
  template:
    metadata:
      name: workout-service-secret
      namespace: fitforge-prod

