---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-secret
  namespace: fitforge-dev
spec:
  encryptedData:
    JWT_SECRET: AgDGWkjqz1jiixdcsY79JJK7plGFSDVUzabEW3Ukg/PrW+wAFHcbKkHVmDIN+iwgXJuu6IgY3gdfnF+3ows2AjEJ1e59h3Z7kTzIkCmhZiR7BFeudL2JF5x+vAFlscV44tA9j0mljvYA/dn+P7hJH+w2aDIe9MGKvuwotWrmzX1SfxB3I09TXDaP441xCN26gEOS1xm4ECl+C2eQzC0NYpFg5/G/UDG5H8x6xtqMk2pMAEvuQ3w6IwgM6i/ClMDd/Er6eMYfMpu6yV4bNl5jfo2kh3FjGhvkE/FriqSG6VQfDBuVovVceSU6f3CQ2y31HGMrRshUlv70v8MSuSe2kGUrDEx8978UvVmUTM5Q3rOjGqyky06T4X9OMpciizT1/EJtcECKq8cHI8jKasjb9ZhS+ugMIXEMnNQbIGwjQ3t1RAFjshtm09v3xt6LnFivXF8ir4P41HyDqWBV7HvQyQNpOZYErGUvC9ILImEz0zKOeFg5XpGaNYX99Wb6rH/zGYW5wUX8O2a7l2Cb/PMoJlEmOAC1tAPEQXlDoKh5bNA3Y03S4oa7wuKYlzSWJ+t0K44TlKi2ArraEX6Gj/s+j34D60Uw+HLTcysj7Cz/fdzFXUqRnyGsht7hC0APFH5cjx1guiAUiARIlgn9Hbfxt3qbB+1Rw/Sw/dJFlj2rnYxdn4Ycb8d8vdZPAe/k+iPxyOpI2/EHn1r3X3zqaQIPgDxzSCYXEsQnzE0yaYoI87Xt8j7w
    MONGO_URI: AgAIsONYHfucAeO9GITfzmIS5eFPb/619sj77n73kE1UCnkiC6yWWIl+aEXG6dyTvPCTFKt12fu01r3xr9Tzw/RMSB4XG6J08hyFtaLgqcc106wZWa4vbs6iMc69rclS9yhA+Xb/LLY3HioIXOfamxPy/tp77X279lyuQTez8dQzeh2Pk3he/qzWF/wTV4Yyvut1rrWifo2ZsYWXqNrng2+r7bWXUKVpFCe6WdAVZ7JJh1y6BUjzFwA6/1yKPfGQ4NJ6HNKOspLQS9tI7dwW/fDmvvOFlp2sWLTImscBrGqtjPyj/62u9UqO1iL3n7sozPCmRC8CXYsNZbvrqUJ/MwYpayQB1PWRepLVRIVCJvjtJaFZ//9r/Wal0zudB7KL5LGLbNLIiKxFQwfvcpmJq6Iy04NRhDPP1hOeWS6vuPeFx1PEBUB892vb2NHq1dQ9eul8Uc8SxzcXbSAsoF8xXjddaWY2V2QdZInCFCXL5bd4A/v/sP8hC8BRj0iE07wWVVrCvz6cnKbcTNMXXgfpZ4U+hrV1ZeCfw97NB1TXcIKH3n1oWKFcQtCiOOWBYlcvmHxB/p8yOgwKoxuHGnzZoADZBBtgjiM+DXqDEDOV+BIgXGlZtBfYD/yjJ1hCn3gHOxlqCsSzRCddQ+KY+oYwMb9/uoTMBsbx+gocF3czxOnwLrs0D7P1ODmLXHQztn7BLkZj+DvptyLe/NGGZGO6WcRqUr/QYxaWRbn0YD0TSlyePh6I9O+eDFJjZ4WzXiw/DnEzFstabpmBWeyhgF8sEKGR8vKD5mDd9RVg7sTbyrAfOUMEIxzLYCoEuhJghpJnvtF4WI2o3nBjPkyMN1qRhNfISm6TdbhbzP0=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service
      name: user-service-secret
      namespace: fitforge-dev
    type: Opaque
