# ---
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   creationTimestamp: null
#   name: user-service-secret
#   namespace: fitforge-prod
# spec:
#   encryptedData:
#     JWT_SECRET: AgDGWkjqz1jiixdcsY79JJK7plGFSDVUzabEW3Ukg/PrW+wAFHcbKkHVmDIN+iwgXJuu6IgY3gdfnF+3ows2AjEJ1e59h3Z7kTzIkCmhZiR7BFeudL2JF5x+vAFlscV44tA9j0mljvYA/dn+P7hJH+w2aDIe9MGKvuwotWrmzX1SfxB3I09TXDaP441xCN26gEOS1xm4ECl+C2eQzC0NYpFg5/G/UDG5H8x6xtqMk2pMAEvuQ3w6IwgM6i/ClMDd/Er6eMYfMpu6yV4bNl5jfo2kh3FjGhvkE/FriqSG6VQfDBuVovVceSU6f3CQ2y31HGMrRshUlv70v8MSuSe2kGUrDEx8978UvVmUTM5Q3rOjGqyky06T4X9OMpciizT1/EJtcECKq8cHI8jKasjb9ZhS+ugMIXEMnNQbIGwjQ3t1RAFjshtm09v3xt6LnFivXF8ir4P41HyDqWBV7HvQyQNpOZYErGUvC9ILImEz0zKOeFg5XpGaNYX99Wb6rH/zGYW5wUX8O2a7l2Cb/PMoJlEmOAC1tAPEQXlDoKh5bNA3Y03S4oa7wuKYlzSWJ+t0K44TlKi2ArraEX6Gj/s+j34D60Uw+HLTcysj7Cz/fdzFXUqRnyGsht7hC0APFH5cjx1guiAUiARIlgn9Hbfxt3qbB+1Rw/Sw/dJFlj2rnYxdn4Ycb8d8vdZPAe/k+iPxyOpI2/EHn1r3X3zqaQIPgDxzSCYXEsQnzE0yaYoI87Xt8j7w
#     MONGO_URI: AgAIsONYHfucAeO9GITfzmIS5eFPb/619sj77n73kE1UCnkiC6yWWIl+aEXG6dyTvPCTFKt12fu01r3xr9Tzw/RMSB4XG6J08hyFtaLgqcc106wZWa4vbs6iMc69rclS9yhA+Xb/LLY3HioIXOfamxPy/tp77X279lyuQTez8dQzeh2Pk3he/qzWF/wTV4Yyvut1rrWifo2ZsYWXqNrng2+r7bWXUKVpFCe6WdAVZ7JJh1y6BUjzFwA6/1yKPfGQ4NJ6HNKOspLQS9tI7dwW/fDmvvOFlp2sWLTImscBrGqtjPyj/62u9UqO1iL3n7sozPCmRC8CXYsNZbvrqUJ/MwYpayQB1PWRepLVRIVCJvjtJaFZ//9r/Wal0zudB7KL5LGLbNLIiKxFQwfvcpmJq6Iy04NRhDPP1hOeWS6vuPeFx1PEBUB892vb2NHq1dQ9eul8Uc8SxzcXbSAsoF8xXjddaWY2V2QdZInCFCXL5bd4A/v/sP8hC8BRj0iE07wWVVrCvz6cnKbcTNMXXgfpZ4U+hrV1ZeCfw97NB1TXcIKH3n1oWKFcQtCiOOWBYlcvmHxB/p8yOgwKoxuHGnzZoADZBBtgjiM+DXqDEDOV+BIgXGlZtBfYD/yjJ1hCn3gHOxlqCsSzRCddQ+KY+oYwMb9/uoTMBsbx+gocF3czxOnwLrs0D7P1ODmLXHQztn7BLkZj+DvptyLe/NGGZGO6WcRqUr/QYxaWRbn0YD0TSlyePh6I9O+eDFJjZ4WzXiw/DnEzFstabpmBWeyhgF8sEKGR8vKD5mDd9RVg7sTbyrAfOUMEIxzLYCoEuhJghpJnvtF4WI2o3nBjPkyMN1qRhNfISm6TdbhbzP0=
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: user-service
#       name: user-service-secret
#       namespace: fitforge-prod
#     type: Opaque


---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-service-secret
  namespace: fitforge-prod
spec:
  encryptedData:
    JWT_SECRET: AgATgzrPwDfwygHVROoSnPyR+YorDFD34ier5K4qW8lk7wJdfZv24lwbnH85pOFSf4U6tN6X+2UvgyaRLmRjYXHREqSNuUL7ijFlCSlL3g/XL7D7OIbJ6wL/PGn8eoC/oMu9aW9UTZqsbgLzlJ/x6qAZrkEB1K9m0gORsNzYRI5aesATtCR1a3PUdEf9HwR5CNa0vDUOPY+VAvxGFoC+x2lXI+/Kax7DXKf5k/myNJ+RUiWjoTJUrUiynSWnWEWmfundaHqGJa3k+Xk/ajotTulsaYH6/FmTeLpeV6Pi+HeUbKr34MMP0W1ynLNqoJGWCvFxkOtPmRdN118WAsG64H36miT0ChR+qbvBszj+J778/Aabu05w3jbdK4yvUD/k4r3Mul4cqw4uxBSy/jGpoggzhWynNHZeeDHEh0yKTDqB4eSh2atoFwlqwKVRGHC3sYo9uCmPmj0Xq/BuNjYumsYOkh4bPaI29MVzPxJa0pH1mCsk5yk3i1j6/xKDEtkuaj94ETTKYyZfiOjUhv93ryl4DwEGpmTpCcAbY2JU2NI+g7ixeu7GxHfxq5plL+TTFJrbOgFy0DyGFwF8N67HjYmDXjuRo0uIymN/4jaulOXsgWDmfHa6gVfqCbc/FUaZrzTk0cw7d/b+63JsDwHGQ0k9/IiiKLafxUD81s1Z+Ny/Huvy3HACIgd7T9XUnc0gSi8gwC2aDG7hK39/+aQ1pF4dV561CtnPy+NdUmiKDGrqANhj
    MONGO_URI: AgC0solaPz66CJO3qyMwHH6YLbTzV5mz3+gq+p+XCI5vCtetUl5YidFmvU11cjm823seb3hHimiSjCA8EG5VNxTBqH5fSpb2bffFm4XTgqeP9nG2jH3e5PJovfPGkAnI0IJg1FnJ0U+paK6wJvKtpgmwFfzveslWv6rn+qHiqRgma2UTP9JdXHZxsIo4y8QiJsGfwcDi5v7lYW7G1044S6uHhqDP+XIQHUgLsC+QRl/554H6LdzKBCtpDmxsOb+fcFUc2fTCmLT16Tjtt/cWIll+iE7yD9g4B13Srzopyo+x96R5KUhBNdx6MTY7viVIMIFyvAy5iobALYpSZElh7okt40jxvDTXxBHfTptrWVeLcZnbPOGEBeEOjkEP0eLv6/F8druLlsggYtFCZA3RN3F10dYHzOyWD6WI9dKojGF0RGIr5Kgk9TzIXRjsIOBbOVckEJNDa2bj2AoBJmjMggWuyFHO/jnK+NsalpvLd8SrDd/mIU0Rsnhbrb5o6HFU/SMecMjZoCk9EGZrrTSczsqmva9h5JJqFaGWhFYSBd7ZZNBT8hGjkfoCet8ElE91ozSwq0sPSNJ9tJtURdzhoxsFPcar1V9KXzkpa2fPfvrIq4o4afZlZLQLhc+sBivvRhc09hixpGnOdnIC3ikmTpqLwKoNg4oAggRnQXSJ3K1iJAvHn8Cy/LV3BuBizdz883xYrdhYOPHY97WmUk4CrGqp1EueqExwdrr86fFjZ6f5f7h/QvMSntoF207/E/KB8g6NyhtKEzYCIoUlxVB/UYZ2awJetVxEu/jlTNxaN0xolt3BcqExy+t0R5FN3xxgMEf75UjRJmqmf8o7Vzk4GtGo2kTfERn3iHLS
  template:
    metadata:
      name: user-service-secret
      namespace: fitforge-prod
