---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-secret
  namespace: fitforge-dev
spec:
  encryptedData:
    JWT_SECRET: AgAEGKGDxeghYqdPTmin8bbhA0C18aN3oMs3sS8OaqUuTVIGBu9CzHC07dWCNEBVznU8mLN55PR9svuYyBkEFgRyeOW34ajF7RDqVLOIr0mfy1DQGsZr/UvlfZYBWsBylgvNCEmkEX2Vym/uaEQHN/E93P7wM45ZOquKDqPvuSGXQidHj3TlQaFcgsPxwQWb+TfQP5sbYwLr95Z27QgyafLt241skofpl2g/iWAEKWtgv0oCC0TYOuW2jrQCvuA9o4FSnwtWSH7WM0v70K9HdOVMgN6J8B5XOEdkjf7NcxPXDWlCvFzbv9FYAnGIcwYcYvdnWmoU4IklfdISejqRUKlxdCvZqDHsJiODmEPqBdZx1wPTf8A5BG2dqyCsX1SqYqej0dkz4U4ll5RvAdsVM7TvZw9QSsZpZk4ELiyxXo5hy65jgh0k4iBhtT+ZbkVdkvj3KQwGsj99uOWFy2Csmd6TTwlMxquDYCqxr+e1LAcc+Mf1L2Az38eN/as4KKNXX943E9wEpVmc6xlxGOeAAR0aBaMcGyTDJOgtVx/+2ZA+U7dCYjHGmOJwBHtCWrqOWa100y3IzZmo8nIlfakN+rxRasr/xeNE/L3ogEcnvQvF3TdC6T53ojQUPxo9f59cP2JtUGMeBEzFwpPCB8r4HHK8ON0ik2TCyW07PfkmXUDV5hb9jHHIgy5jDQKHnCG8nkHD1y72qXlzwyQfouUM6jio1LR43+pUGsYtD5bhn6Vb+LHI
    MONGO_URI: AgDKlc40vX2VeSUd2GgvQ297YpJEXqUVgsbCahYwiwA38ylIoJPNyxLG7gEiGUDL16UWkIaI+eErRPojyZSlkJItm4rdB31bCsK2n6fh4XM5GOlvsbIg0OIqUPK/Jn0TnqhZqRc7nPLrBkgqUFz/WAVt7bXsBLC3Gr54Nd8fjb1aYWTkX5t/pXN9gwI7szLNemsmtLIFrQDuWBx+WEslOf51GdmcjnhXYudfc00MOgvVPk54ln+/PLi/haDbWjeoAuQqoeyXMKSYxUb5U/HkWJjKRYd8ZhNeI1mfEc+vVIeCNBIAXj8tOMt47pVwEd5YycitlkW66Y/g+eldgRw6ajUYK3s8TVq9eNEgnNiyuu9+FHkRPNXZwi13L2SU3c2XAJzVSCMVjY+D5jgfHdy3ma/SPxJQX94LVXTs86AwtaBJNGtY4uc6O5wjVvvQXu1/ecKlTC2yiM6yHsfldoOBUuB6wzzOB7+mDaU6maK2RYgrXJn6mFGBOY+9NnAJb9jmIaS5AvFYlBv+hELIkSRBF2re6k6VUdSRRekt+CRJWbL+bcV7rw6Up0zOmgcbmRkL5G6kUklkZpVUa7Sc01478xuDcePJazXSocSec4QO/tMYrs6BbCgljfFWtg5TQksCx0iGJXNW6HhN9RbRYSyOLDDUQ+6dDlECztN7N6e71U6/06gv6yrFY5bW3VWYFqzP1JDHmy+8EzxMsGmxBBPTNijO7Yg1XLFCnYHD8/RQcLG+AVOQHPvVhNAPTMd0Mq+taZTq9jhsWTav091EtC0Zgd0F9uJpuLrQqdrTzcmMjTMcjkHGvtpvIoS2a5xw6/F6NdCeHCrNeWJYOClvzUDRL88gwxy6t8KI
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service
      name: user-service-secret
      namespace: fitforge-dev
    type: Opaque
