# ---
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   creationTimestamp: null
#   name: auth-service-secret
#   namespace: fitforge-prod
# spec:
#   encryptedData:
#     JWT_SECRET: AgAbj+F5vguwpoaMQ1jmuh9HytvFrRKIGvmbYRd7TP2yFA7Zz+p0dl9hSrGvhc4/KzKNu+HXZizNsK+Pd2L/ZjxtWeILiun6Vnv4YUJwiIh8/AREhZktS78h2KRM0rJvDAptu9n/aKKWE0ioPSoOPQun/4lfioVAB/8qx20Qjk6LAtPsBn4ciht1CIsR6La+Qi3n4GrhCvQuP4rJZ2wxl515UuyliwjnTEU2kaAwXZfR8EMYYbJDA2UUC/EfeL4PbDhQZTN44Y05YVCsLgn/cdbEDn1mR0Evct14jxMlTnede677nlLB4hZh145BNjPoULPFrfomhbuXu4OMZbZU6ACLkNYdgezHwNSAMyzahWSWu9pj8/qkx0V7HBHZuPmzhITLhHz2FgPpn6+bjEV0x9nxzpQHDteQBOO3UVcGTQBVptahLczX7DLK4CoEpQwQQaeXDVUToqNM0iXoVB7XYFe4H2fGKRw94LgLSY8tFpYTW5aZ/CFe90ZOw91C10MUgolBbvs2qob1y9Ws3iJ2SB27bgUZuFyTwDYzfqoWq47vsPP/oKupGXKVeRdroA5lshsXFg6T0ckWDGYI2zqVfEHG1zUKEY+2/drb04povqsdhIaiVmrNBiqiy8frCBE2SiCG7x/+e6EbO8UrKOEgZB6BX7KtBIxDMuVFAZrImrfiOqssoTeeyi3o95M8XsXzcJA+oqGOoWoJrIAxQVF8biP8tQxudVySYLtvaehdPpUCXuv/
#     MONGO_URI: AgDYV+t+sSd3FBBne3rmIQBHL9dhtH8s6vwNDTT5/DwlYskhZoL7wbYwkuCEzUn69uRj88KFThwWeGX6r8Gb0frNPIKUlhXXvTP0CK3mx9W2YSCDN9m3BoSl6xRJebC6/3QDPl+9jnIPsr8WG0sH14TopkkU7gQUIs4xTLYpMxShEahThbupxlGSJfz1xyJ1LTkc9DgARSyqu8YldfNfzV907LVhCqUhfP6uxSI7+csva12Ld3fN1oCuVjkkfdkFOfx1K3FbwhaeNjheJIABrErE1vrYwISsJHajr8IjJ//daGthLO05iZsre8F6B3ku9JmIvW8cYIVPQqbGjCzhrBWaMrejYUmGJHaXo1p5CxwP0w28bTk15g77vbhs+BsIIsKpevTApioADbEfgnXFENTQItYu1HR5VE7wHoP19NzaeAmDsOD20ose9LRbjB8BEMw5wuD84HfgtoYlv1osR0A8JIHn8JI/q3dDTAXcNbcol78n3oLMFE0bvW0Lg9RlKgPNNhDSII68KqWVizOLA2JA64eDZghPNbO8pT0KkKjKOIhL6MIFAx7Rfb24NRF6xHSmzLg4fU1hh7fDU+NpeMSZ4Xu1yIa+L9mWCqqUfHYvVtbqpjNuRlNIMhjg2mCdR3fcEEfZNGlB+TZbWAAaQX2iXADdBu/JDXVVtXNoWP1arc9e0EFd0/CCSRYk4ZNlE/riALbh7I0AnkiaE3YigMuxjcfPolWTlydf6l+klMNkaIfoH3BKHihOExLUg42S9L6qiTMhQVF+kfGTS6z1voSVcW8f5KvFxhmhTOPCAA+s552COJXwDiSZMtCPRmL4djGL+/evO7Zt5P6tY51bDBIfQkeHYk1rSCw=
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: auth-service
#       name: auth-service-secret
#       namespace: fitforge-prod
#     type: Opaque


---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-secret
  namespace: fitforge-prod
spec:
  encryptedData:
    JWT_SECRET: AgA3dogSH3eOPRFuE4TSGtJIfaQrny+0FLCiqz5bLYwYw918KjRBOQdyFp0MX+V73mWFgbLA13OgGAEJ0qEd4ycuTtHzTuUjRfXZt0w+WNYLA6x12gxUYQ0Cy/mVRKUV666wKm9pvAea69B6L++VCyMXIwo6JEuP+I8UO8Nj1Qe8kKfaCEpUNg/yKQHxYUvjiWav99uCBP2mOq3WfikEzc7UZxpgTR2/WhLNUYnr2qh1J5bNJDG1DZfzDrJRBKz+GX2w2N1voY0pMRqoGJvTXLPh5diRLMocWu5O4u/O3f+j606PLrFBoCx5dLRpeMWLEglXe5JmtL0QWQ4BEwssfpW7j3whImxTlZVXeu49OYZMS2S4Y+Iw/ZLWZtpti9h68Hj7adncXGVzEhznbOwDT5lSRCM+SaCm15MG0/LgCPG+Wrhz60m6KO00zill1529fHMKv6bO85BkjWelMDZkaj0y/naIDSkX2VQlOoACoCgB8lTaLkNzwICLdW+C1XS9RJlLqocbEje3yDj0lENEQY48WcZ5Mq7B2SanDXaCbH0iaI7fBGOGwbVed0NGNAzxXI7Ebku4dD9/1MMlIud6x/WwlxYWo1d4TkuibDavX+Ol7U8qGX9SnXhk229GWoEZo4K/qMX5fSw8azOKTjbr7fGDZZ0rWVjjcymGKniFD543U0bk0JZX4Q5B5/hqV6C/8nDxX388Vilo4M1awu/S6VUXJzfnWOCN0wkIOOlbJ74t1d4p
    MONGO_URI: AgBIWCCGT+mHRq1aPpswMxpbo+z6P4ATS8vgGt65PYrS97tvApfpXasIkGl/kw5BzhQfLS3muybLG+32ktqsOl9YEHLblFkvTuPXLxWK0AX1FijJFFOAj1gZlNqEcmfWmrnL90JjUliTLXuQ2LGIwVJGj/hhoKps4EKBQKJFcqJOz6evbo2vkDRCdz2mB0YfYLVuO6vfDYVSCIbjtjaKDPaPFJlhiW06DfUNffSCoAhWVR4wd1KTvMu3Uqo+nITwxvDm7vZ7GvNQiU5zJ65pOjvc3wsnnXyC/LBJTmnNwgOU2KJFi1oqC8hUybIEV+qcz6eybgQnIaeGdZpZ2EvLeTL6Pg4QihJspW3rlzXabsuT9b7CQ1iFU4XNIKGxZaMCs06pN+9EbqA0GenB0sxdje032KKnSL8x9/m3ESmrjDh2ihxzdC06VmVWWg27ZczGSM/7bpojXE1HTpqYtoZMJjvjESTSYwgtqyPOqhDF69G29AbVdK09taNjgzI1D6a3J7MV3TBJ/1mOEycTsV9/rSbXYye3Fk8gSE+Vj+YroBo839rhKlW0zDZTEgEBRpqtLvQhjeKFVGWrOuO5hCNsj+Vem+9nnle+SU/snhpTGqML7PbH7QUuWQSRV5dOKy/zQ8nnxuN165t1As0n9A9zMukghJh+mNJB0jYgVCWua5yarnf49oI8xPmmvin6T9BRsJrA9FhWT9UNnbUg8MnsQXqDxZAE6lcJhuiceut0zJyeUQqdxt6dT/qF4E4wsoUE4RUJ9mq7PIEphoUo87A9RHL+JZFyPrx7HVDIVjhQE6+xVmYBfp6dpEAlQasfyYVv2h+Pkz9rArzeEhynhmdlCCvCH5jwrV6HHb4d
  template:
    metadata:
      name: auth-service-secret
      namespace: fitforge-prod

