---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: fitforge-prod
spec:
  encryptedData:
    JWT_SECRET: AgAbj+F5vguwpoaMQ1jmuh9HytvFrRKIGvmbYRd7TP2yFA7Zz+p0dl9hSrGvhc4/KzKNu+HXZizNsK+Pd2L/ZjxtWeILiun6Vnv4YUJwiIh8/AREhZktS78h2KRM0rJvDAptu9n/aKKWE0ioPSoOPQun/4lfioVAB/8qx20Qjk6LAtPsBn4ciht1CIsR6La+Qi3n4GrhCvQuP4rJZ2wxl515UuyliwjnTEU2kaAwXZfR8EMYYbJDA2UUC/EfeL4PbDhQZTN44Y05YVCsLgn/cdbEDn1mR0Evct14jxMlTnede677nlLB4hZh145BNjPoULPFrfomhbuXu4OMZbZU6ACLkNYdgezHwNSAMyzahWSWu9pj8/qkx0V7HBHZuPmzhITLhHz2FgPpn6+bjEV0x9nxzpQHDteQBOO3UVcGTQBVptahLczX7DLK4CoEpQwQQaeXDVUToqNM0iXoVB7XYFe4H2fGKRw94LgLSY8tFpYTW5aZ/CFe90ZOw91C10MUgolBbvs2qob1y9Ws3iJ2SB27bgUZuFyTwDYzfqoWq47vsPP/oKupGXKVeRdroA5lshsXFg6T0ckWDGYI2zqVfEHG1zUKEY+2/drb04povqsdhIaiVmrNBiqiy8frCBE2SiCG7x/+e6EbO8UrKOEgZB6BX7KtBIxDMuVFAZrImrfiOqssoTeeyi3o95M8XsXzcJA+oqGOoWoJrIAxQVF8biP8tQxudVySYLtvaehdPpUCXuv/
    MONGO_URI: AgDYV+t+sSd3FBBne3rmIQBHL9dhtH8s6vwNDTT5/DwlYskhZoL7wbYwkuCEzUn69uRj88KFThwWeGX6r8Gb0frNPIKUlhXXvTP0CK3mx9W2YSCDN9m3BoSl6xRJebC6/3QDPl+9jnIPsr8WG0sH14TopkkU7gQUIs4xTLYpMxShEahThbupxlGSJfz1xyJ1LTkc9DgARSyqu8YldfNfzV907LVhCqUhfP6uxSI7+csva12Ld3fN1oCuVjkkfdkFOfx1K3FbwhaeNjheJIABrErE1vrYwISsJHajr8IjJ//daGthLO05iZsre8F6B3ku9JmIvW8cYIVPQqbGjCzhrBWaMrejYUmGJHaXo1p5CxwP0w28bTk15g77vbhs+BsIIsKpevTApioADbEfgnXFENTQItYu1HR5VE7wHoP19NzaeAmDsOD20ose9LRbjB8BEMw5wuD84HfgtoYlv1osR0A8JIHn8JI/q3dDTAXcNbcol78n3oLMFE0bvW0Lg9RlKgPNNhDSII68KqWVizOLA2JA64eDZghPNbO8pT0KkKjKOIhL6MIFAx7Rfb24NRF6xHSmzLg4fU1hh7fDU+NpeMSZ4Xu1yIa+L9mWCqqUfHYvVtbqpjNuRlNIMhjg2mCdR3fcEEfZNGlB+TZbWAAaQX2iXADdBu/JDXVVtXNoWP1arc9e0EFd0/CCSRYk4ZNlE/riALbh7I0AnkiaE3YigMuxjcfPolWTlydf6l+klMNkaIfoH3BKHihOExLUg42S9L6qiTMhQVF+kfGTS6z1voSVcW8f5KvFxhmhTOPCAA+s552COJXwDiSZMtCPRmL4djGL+/evO7Zt5P6tY51bDBIfQkeHYk1rSCw=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-service
      name: auth-service-secret
      namespace: fitforge-prod
    type: Opaque
